# Generated by Django 5.2.1 on 2025-05-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeapp', '0002_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
