# Generated by Django 5.2.1 on 2025-05-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeapp', '0003_correction_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('grandfathername', models.CharField(max_length=100)),
            ],
        ),
    ]
