# Generated by Django 5.2.1 on 2025-05-28 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treeapp', '0005_helprequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correction',
            options={'verbose_name': 'Name Correction Request', 'verbose_name_plural': 'Name Correction Requests'},
        ),
    ]
