# Generated by Django 5.2.1 on 2025-05-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treeapp', '0006_alter_correction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addmember',
            options={'verbose_name': 'Request to Add Member', 'verbose_name_plural': 'Requests to Add Members'},
        ),
    ]
