# Generated by Django 5.2.1 on 2025-06-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeapp', '0007_alter_addmember_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='family_photos/'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='year_of_death',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
