# Generated by Django 5.2.1 on 2025-06-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treeapp', '0012_userprofile_last_child'),
        ('treeapp', '0013_userprofile_last_child'),
    ]

    operations = [
    ]
