# Generated by Django 5.2.1 on 2025-06-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treeapp', '0017_userprofile_name'),
        ('treeapp', '0017_userprofile_name_userprofile_plain_password'),
    ]

    operations = [
    ]
