# Generated by Django 5.2 on 2025-06-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeapp', '0020_userprofile_blood_group_userprofile_is_blood_donor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='is_registered_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='needed_where',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='urgency',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10, null=True),
        ),
    ]
