# Generated by Django 5.1.1 on 2025-06-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeapp', '0022_album_albumphoto_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hide_from_donor_list',
            field=models.BooleanField(default=False),
        ),
    ]
