# Generated by Django 5.1.1 on 2025-06-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeapp', '0026_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
