# Generated by Django 5.1.1 on 2025-06-13 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeapp', '0029_alter_familymember_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='treeapp.familymember'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='year_of_death',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
