# Generated by Django 5.1.1 on 2025-06-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeapp', '0035_committeemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='designation',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
